# Generated by Django 3.0.5 on 2021-01-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevote',
            name='site',
        ),
        migrations.AddField(
            model_name='sitevote',
            name='page',
            field=models.TextField(default='invalid page'),
        ),
    ]
