# Generated by Django 3.0.5 on 2021-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20210111_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevote',
            name='domain',
            field=models.TextField(default='not a domain'),
        ),
    ]
