# Generated by Django 3.0.5 on 2021-01-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='clean_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
